# Generated by Django 5.0.6 on 2024-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabapp', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('medicalhistory', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Email',
            new_name='email',
        ),
    ]
